storage:
    type: file
    name: worldprotect
    hosts:
        - localhost:27017
    ssl: false
world:
    flags:
        default:
            - burn
            - bukkitEmptyLava
            - entityBlockExplode
            - portalCreation
region:
    worlds:
        - world
        - world_nether
        - world_the_end
    maxPerPlayer: 8
    maxVolume: 30000
    tool: STICK
    flags:
        default:
            - use
            - pvp
            - burn
            - build
            - piston
            - bukkitEmptyLava
            - entityBlockExplode
            - portalCreation
        allowed:
            - pvp
            - piston
            - leavesDecay
            - fallingBlocks
            - vehicleNaturalDestroy
    prevent:
        use:
            - CHEST
            - DISPENSER
            - DROPPER
            - WORKBENCH
            - JUKEBOX
            - BREWING_STAND
            - ANVIL
            - CAULDRON
            - FURNACE
            - FENCE_GATE
            - DROPPER
            - ENCHANTMENT_TABLE
            - STONE_BUTTON
            - WOOD_BUTTON
            - WOOD_DOOR
            - IRON_DOOR
            - TRAP_DOOR
            - ENDER_CHEST
            - BEACON
            - WOODEN_DOOR
            - GOLD_PLATE
            - IRON_PLATE
            - FURNACE
            - BURNING_FURNACE
        commands:
            - sethome
messages:
    error_worldedit_not_found: "&4Плагин WorldEdit не найден."
    error_player_not_found: "&4Игрок с именем %s не зарегистрирован."
    error_unknown_command: "&4Неизвестная комманда. Посмотреть список доступных комманд /%s help"
    error_region_selection: "&4Сначала выделите регион."
    error_region_overlay: "&4Регион пересекается с другим."
    error_region_not_found: "&4Регион в этой области не существует."
    error_region_name_exists: "&4Регион с именем %s уже создан."
    error_region_created_max: "&4Вы создали максимальное количество регионов %d."
    error_input_region_name: "&4Введите имя региона."
    error_input_player: "&4Введите имя игрока."
    error_input_region_not_found: "&4Регион %s не найден."
    error_input_flag_unknown: "&4Неизвестный флаг %s."
    error_input_flag_invalid_value: "&4Некорректное значение флага %s."
    error_input_flag: "&4Введите название флага."
    error_input_flag_value: "&4Введите значение флага."
    error_input_world_name: " &4Введите имя мира."
    error_input_world_not_found: "&4Мир %s не найден."
    error_region_contains_player: "&4Игрок %s уже добавлен в регион %s в роле %s."
    error_region_player_exists: "&4Игрока %s нет в регионе %s."
    error_region_protected: "&4У вас нет прав на редактирование этого региона."
    error_regions_disabled: "&4В мире %s создание регионов отключено."
    error_no_permission: "&4У вас нет прав на использования этой комманды."
    error_command_disabled: "&4У вас нет прав использовать комманду /%s в этом регионе."
    error_pvp_disabled: "&4PVP отключен в этом регионе."
    error_region_max_volume: "&4Максимальный объём региона %s, ваш регион %s."
    error_player_command: "&4Комманда доступна только для игроков."
    error_cant_build: "&4Вы не можете здесь строить."
    error_unsupported_convert: "&4Поддерживается только конвертация из %s в %s."
    error_emergency: "$4Аварийная ситуация, мы уже работаем над её исправлением."
    success_region_flag_set: "&2Флаг %s в регионе %s установлен в значение %s."
    success_region_created: "&2Регион %s создан."
    success_region_deleted: "&2Регион %s удален."
    success_region_player_add: "&2Игрок %s добавлен в регион %s."
    success_region_player_delete: "&2Игрок %s удален из региона %s."
    success_saved: "&2Сохранено."
    success_world_flag_set: "&2Флаг %s в мире %s установлен в значение %s."
    region_name: "Регион"
    region_own_list: "Список регионов принадлежащих вам"
    region_size: "Размер"
    region_owners: "Владельцы"
    region_members: "Игроки"
    flags: "Флаги"
    flag_true: "запрещено"
    flag_false: "разрешено"
    role_owner: "владельца"
    role_member: "игрока"
