world:
    flags:
        default:
            - burn
            - bukkitEmptyLava
            - entityBlockExplode
            - portalCreation
region:
    worlds:
        - world
        - world_nether
        - world_the_end
    maxPerPlayer: 8
    maxVolume: 30000
    tool: STICK
    flags:
        default:
            - use
            - pvp
            - burn
            - build
            - piston
            - bukkitEmptyLava
            - entityBlockExplode
            - portalCreation
        allowed:
            - pvp
            - piston
            - vehicleNaturalDestroy
    prevent:
        use:
            - CHEST
            - DISPENSER
            - DROPPER
            - WORKBENCH
            - JUKEBOX
            - BREWING_STAND
            - ANVIL
            - CAULDRON
            - FURNACE
            - FENCE_GATE
            - DROPPER
            - ENCHANTMENT_TABLE
            - STONE_BUTTON
            - WOOD_BUTTON
            - WOOD_DOOR
            - IRON_DOOR
            - TRAP_DOOR
            - ENDER_CHEST
            - BEACON
            - WOODEN_DOOR
            - GOLD_PLATE
            - IRON_PLATE
            - FURNACE
            - BURNING_FURNACE
        commands:
            - sethome

