name: ${artifactId}
main: ${groupId}.${artifactId}
author: Mete0 <admin@gtn-craft.ru>
version: ${version}
softdepend: [ WorldEdit ]

permissions:
    worldprotect.admin:
        description: Полное управление регионами.
        default: op
    worldprotect.moder:
        description: Модерирование регионов.
        default: false
    worldprotect.use:
        description: Доступ к использованию комманд управления регионами.
        default: true
commands:
    region:
        aliases: [ rg ]
        description: Комманды управления регионами.
        permission: worldprotect.use
        usage: |
             /<command> define <регион> - Создать регион.
             /<command> delete <регион> - Удалить регион.
             /<command> addowner <регион> <игрок> - Добавить владельца региона.
             /<command> deleteowner <регион> <игрок> - Удалить владельца региона.
             /<command> addmember <регион> <игрок> - Добавить игрока в регион.
             /<command> deletemember <регион> <игрок> - Удалить игрока из региона.
             /<command> info [регион] - Показать информацию о регионе.
             /<command> list - Показать список доступных вам регионов.
             /<command> flag <регион> set <флаг> <true|false> - Установить флаг для региона.
             /<command> help - Показать список комманд.
    worldprotect:
        aliases: [ wp ]
        description: Комманды управления плагином.
        permission: worldprotect.admin
        usage: |
             /<command> save - Сохранить регионы.
             /<command> convert - Сконвертировать регионы из mongodb в локальные файлы.
             /<command> info [мир] - Показать установленные флаги в мире.
             /<command> flag <мир> set <флаг> <true|false> - Установить флаг для мира.
             /<command> help - Показать список комманд.
