name: WorldProtect
main: ru.gtncraft.worldprotect.WorldProtect
author: Mete0 <admin@gtn-craft.ru>
version: ${version}

permissions:
    worldprotect.admin:
        description: Allow administrate user regions.
        default: op
    worldprotect.use:
        description: Allow use region commands.
        default: true

commands:
    region:
        aliases: [ rg ]
        description: Commands for manipulating regions.
        permission: worldprotect.use
        usage: |
             /<command> define [регион] - Создать регион.
             /<command> del [регион] - Удалить регион.
             /<command> addowner [регион] [игрок] - Добавить владельца региона.
             /<command> delowner [регион] [игрок] - Удалить владельца региона.
             /<command> addmember [регион] [игрок] - Добавить игрока в регион.
             /<command> delmember [регион] [игрок] - Удалить игрока из региона.
             /<command> info <регион> - Показать информацию о регионе.
             /<command> list - Показать список доступных вам регионов.
             /<command> flag [регион] set [flag] [значение] - Установить флаг для региона.

